language: r
warnings_are_errors: true
sudo: required
cache: packages
dist: trusty

matrix:
    include:
        - os: linux
          r: release
          env: R_CODECOV=true

r_packages:
      - covr

after_success:
      - Rscript -e 'library(covr); codecov()'
